version: "8.0.33"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "5433:5432"
    environment:
      MYSQLDB_USER: $MYSQLDB_USER
      MYSQLDB_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQLDB_DATABASE: $MYSQLDB_DATABASE

